"""The figures. Matplotlib, written to `out/figures/`, regenerated by `mselect report`.

Chart rules followed here: one axis per chart and never two y-scales; a fixed categorical
order so a series keeps its colour whatever else is on the chart; thin marks and a recessive
grid; every line directly labelled at its right end, which is also the relief the palette's
contrast warning requires; and a legend whenever more than one series is present.
"""

from __future__ import annotations

from pathlib import Path
from typing import Final

import matplotlib
import numpy as np
import polars as pl

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.axes import Axes
from matplotlib.lines import Line2D

from mselect.irt.model import Items, information, test_information

SERIES = {
    "adaptive": "#2a78d6",
    "stratified": "#eb6834",
    "random": "#1baf7a",
    "random_raw_score": "#eda100",
}
LABELS = {
    "adaptive": "adaptive (IRT)",
    "stratified": "stratified sample",
    "random": "random sample, IRT scored",
    "random_raw_score": "random sample, raw score",
}
INK = "#0b0b0b"
MUTED = "#52514e"
GRID = "#d9d8d4"
# Matplotlib stamps its own version into a PNG text chunk, so a figure regenerated under a
# different patch release differs in bytes while being identical in every pixel. The README says
# these are regenerated with one command; dropping the stamp is what makes that produce no diff
# when nothing has changed, rather than a diff nobody can interpret.
NO_METADATA: Final = {"Software": None}

SURFACE = "#fcfcfb"


def _style(ax: Axes) -> None:
    ax.set_facecolor(SURFACE)
    ax.grid(True, color=GRID, linewidth=0.6, alpha=0.9)
    ax.set_axisbelow(True)
    for side in ("top", "right"):
        ax.spines[side].set_visible(False)
    for side in ("left", "bottom"):
        ax.spines[side].set_color(GRID)
    ax.tick_params(colors=MUTED, labelsize=9)


def headline_curve(curve: pl.DataFrame, full_tau: float, suite_items: int, out: Path) -> Path:
    """Kendall's tau against the full-suite ranking, by number of items, with bootstrap bands."""
    fig, ax = plt.subplots(figsize=(8.2, 5.0), facecolor=SURFACE)
    _style(ax)
    for method, colour in SERIES.items():
        rows = curve.filter(pl.col("method") == method).sort("items")
        if rows.is_empty():
            continue
        x = rows["items"].to_numpy()
        y = rows["tau"].to_numpy()
        ax.fill_between(
            x,
            rows["tau_lo"].to_numpy(),
            rows["tau_hi"].to_numpy(),
            color=colour,
            alpha=0.13,
            linewidth=0,
        )
        ax.plot(x, y, color=colour, linewidth=2.0, marker="o", markersize=4.5)
        if method == "adaptive":
            # Only the adaptive line is labelled in place, at the left where the lines are far
            # apart. At the right they converge into each other and stacked labels there are
            # unreadable; the legend and the README table carry identity instead.
            ax.annotate(
                LABELS[method],
                xy=(x[0], y[0]),
                xytext=(8, 10),
                textcoords="offset points",
                color=colour,
                fontsize=9.5,
                va="center",
            )
    smallest = float(curve["items"].min())  # type: ignore[arg-type]
    largest = float(curve["items"].max())  # type: ignore[arg-type]
    ax.axhline(full_tau, color=MUTED, linewidth=1.2, linestyle=(0, (4, 3)))
    ax.annotate(
        f"ranking on all {suite_items:,} items (tau {full_tau:.3f})",
        xy=(smallest, full_tau),
        xytext=(0, 7),
        textcoords="offset points",
        color=MUTED,
        fontsize=8.5,
    )
    ax.set_xscale("log")
    ax.set_xlabel("items asked of each model", color=MUTED, fontsize=10)
    ax.set_ylabel("Kendall's tau vs the full-suite ranking", color=MUTED, fontsize=10)
    ax.set_title(
        "Adaptive selection wins the small budget, and only the small budget",
        color=INK,
        fontsize=13,
        loc="left",
        pad=14,
    )
    ax.set_xlim(smallest * 0.82, largest * 1.35)
    ax.legend(
        handles=[
            Line2D([], [], color=colour, linewidth=2.0, label=LABELS[method])
            for method, colour in SERIES.items()
        ],
        loc="lower right",
        frameon=False,
        fontsize=9,
        labelcolor=MUTED,
    )
    fig.tight_layout()
    fig.savefig(out, dpi=160, facecolor=SURFACE, metadata=NO_METADATA)
    plt.close(fig)
    return out


def item_parameters(params: pl.DataFrame, out: Path) -> Path:
    """Where the bank's information actually is: discrimination, and the items that have none."""
    a = params["a"].to_numpy()
    b = params["b"].to_numpy()
    fig, axes = plt.subplots(1, 2, figsize=(10.5, 4.4), facecolor=SURFACE)
    for ax in axes:
        _style(ax)

    axes[0].hist(np.clip(a, -1.5, 4.0), bins=70, color=SERIES["adaptive"], alpha=0.85)
    axes[0].axvline(0.3, color=SERIES["stratified"], linewidth=1.6)
    axes[0].annotate(
        f"below 0.3: {(a < 0.3).mean():.0%} of items",
        xy=(0.3, axes[0].get_ylim()[1] * 0.92),
        xytext=(8, 0),
        textcoords="offset points",
        color=MUTED,
        fontsize=9,
    )
    axes[0].set_xlabel("discrimination (a)", color=MUTED, fontsize=10)
    axes[0].set_ylabel("items", color=MUTED, fontsize=10)
    axes[0].set_title(
        "One item in five discriminates below 0.3", color=INK, fontsize=12, loc="left"
    )

    usable = np.isfinite(b) & (a > 0.3)
    dead = np.isfinite(b) & (a <= 0.3)
    axes[1].scatter(b[usable], a[usable], s=4, color=SERIES["adaptive"], alpha=0.25, linewidths=0)
    axes[1].scatter(b[dead], a[dead], s=4, color=SERIES["stratified"], alpha=0.35, linewidths=0)
    axes[1].set_xlim(-8, 8)
    axes[1].set_ylim(-2, 4.5)
    axes[1].set_xlabel("difficulty (b), ability units", color=MUTED, fontsize=10)
    axes[1].set_ylabel("discrimination (a)", color=MUTED, fontsize=10)
    axes[1].set_title("Difficulty against discrimination", color=INK, fontsize=12, loc="left")
    axes[1].legend(
        handles=[
            Line2D(
                [],
                [],
                marker="o",
                linestyle="",
                color=SERIES["adaptive"],
                label="carries information",
            ),
            Line2D(
                [],
                [],
                marker="o",
                linestyle="",
                color=SERIES["stratified"],
                label="a <= 0.3: measures little",
            ),
        ],
        loc="upper right",
        frameon=False,
        fontsize=9,
        labelcolor=MUTED,
    )
    fig.tight_layout()
    fig.savefig(out, dpi=160, facecolor=SURFACE, metadata=NO_METADATA)
    plt.close(fig)
    return out


def information_curve(items: Items, out: Path, *, top: int = 200) -> Path:
    """What the bank can measure, and what the best 200 items can measure, by ability."""
    grid = np.linspace(-3.0, 3.0, 121)
    whole = test_information(grid, items)
    best = np.array([np.sort(information(np.array([t]), items)[0])[::-1][:top].sum() for t in grid])

    fig, ax = plt.subplots(figsize=(8.2, 4.6), facecolor=SURFACE)
    _style(ax)
    ax.plot(grid, whole, color=SERIES["adaptive"], linewidth=2.0)
    ax.plot(grid, best, color=SERIES["stratified"], linewidth=2.0)
    for values, colour, label in (
        (whole, SERIES["adaptive"], f"whole bank ({items.n_items:,} items)"),
        (best, SERIES["stratified"], f"best {top} items at each ability"),
    ):
        peak = int(np.argmax(values))
        ax.annotate(
            label,
            xy=(grid[peak], values[peak]),
            xytext=(0, 12),
            textcoords="offset points",
            ha="center",
            color=colour,
            fontsize=9.5,
        )
    ax.set_yscale("log")
    ax.set_xlabel("model ability (theta)", color=MUTED, fontsize=10)
    ax.set_ylabel("test information", color=MUTED, fontsize=10)
    ax.set_title(
        "The bank measures weak models best and frontier models worst",
        color=INK,
        fontsize=13,
        loc="left",
        pad=12,
    )
    fig.tight_layout()
    fig.savefig(out, dpi=160, facecolor=SURFACE, metadata=NO_METADATA)
    plt.close(fig)
    return out


def local_dependence(summary: dict[str, object], out: Path) -> Path:
    """Share of item pairs with Q3 above 0.2, per benchmark: the assumption being violated."""
    names: list[str] = []
    shares: list[float] = []
    for name, payload in sorted(summary.items()):
        if not isinstance(payload, dict) or "summary" not in payload:
            continue
        stats = payload["summary"]
        if not isinstance(stats, dict):
            continue
        names.append(name)
        shares.append(float(stats.get("share_above_flag", 0.0)) * 100.0)

    fig, ax = plt.subplots(figsize=(8.2, 0.5 * len(names) + 2.0), facecolor=SURFACE)
    _style(ax)
    order = np.argsort(shares)
    positions = np.arange(len(names))
    ax.barh(positions, np.array(shares)[order], color=SERIES["adaptive"], height=0.62)
    ax.set_yticks(positions, [names[i] for i in order], color=MUTED)
    for position, value in zip(positions, np.array(shares)[order], strict=True):
        ax.annotate(
            f"{value:.0f}%",
            xy=(value, position),
            xytext=(5, 0),
            textcoords="offset points",
            va="center",
            color=MUTED,
            fontsize=9,
        )
    ax.set_xlabel("share of item pairs with Q3 above 0.2", color=MUTED, fontsize=10)
    ax.set_title(
        "Items are not independent, and the violation is not small",
        color=INK,
        fontsize=13,
        loc="left",
        pad=12,
    )
    ax.set_xlim(0, max([*shares, 1.0]) * 1.18)
    fig.tight_layout()
    fig.savefig(out, dpi=160, facecolor=SURFACE, metadata=NO_METADATA)
    plt.close(fig)
    return out
